### ISSUE TITLE
Create AnonCredsApi that uses the AnonCreds service and registires to write/read anoncreds objects

### ISSUE THREAD

**Issue by karimStekelenburg** [hyperledger/aries-framework-javascript#1124]
### Description
The `AnonCredsApi` is the public API of the `anoncreds` module. The public methods of the `AnonCredsApi` will be exposed to the user through `agent.anoncreds.*`.

The `AnonCredsApi` will replace the current [`LedgerModule`](https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/ledger/LedgerModule.ts) and will have similar functionality. The `LedgerModule` currently creates storage records for credential definitions and schemas. These should be reused by the `AnonCredsApi`.

For reference, the `AnonCredsApi`  is noted by the arrow in the image below.

<p align="center">
<img src="https://user-images.githubusercontent.com/18397186/204349398-8d51966f-eaba-4f4e-af7b-66cac1c02705.png" width=50% height=50%>
</p>

### Approaches
This task heavily depends on [#1123](https://github.com/hyperledger/aries-framework-javascript/issues/1123) and the approach choices that are being made there.

### Todos
- [ ] Create the `AnonCredsApi`
- [ ] Implement all methods
- [ ] Write tests
- [ ] Remove ledger module

**Comment by TimoGlastra** [comment]
Link to AnonCredsApi interfaces: https://github.com/animo/anoncreds-interfaces/blob/main/src/AnonCredsApi.ts

Not finished yet, but will be updated soon.

**Comment by TimoGlastra** [comment]
Also depends on: https://github.com/hyperledger/aries-framework-javascript/issues/1128
