### ISSUE TITLE
Remove indy-sdk from core

### ISSUE THREAD

**Issue by karimStekelenburg** [hyperledger/aries-framework-javascript#1125]
### Description
One of the things we're trying to achieve is to remove the dependency on the `indy-sdk` Rust library. Instead, the `indy-sdk` related logic will be handled by a set of new components that rely on the newer `indy-vdr`, `aries-askar`, and `anoncreds-rs` Rust libraries. These components should have been finalized in the preceding tasks.

There is a difference, however. Currently, the `core` of AFJ depends on `indy-sdk`, which is provided through the `indy` property inside the [`AgentDependencies`](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/core/src/agent/AgentDependencies.ts#L11) object. In order to make the framework more flexible, this will not be replaced `indy-vdr`, `aries-askar`, and `anoncreds-rs` dependencies. Instead, we will have new `packages` (or modules) that depend on these libraries, and users can provide these modules to the agent upon initialization.

Assuming the other components are in place, as a final step we need to remove the `indy-sdk` from the [`AgentDependencies`](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/core/src/agent/AgentDependencies.ts#L11). This will likely cause some issues that need to be addressed.

### Todos

- [ ] Remove the `indy` property from  [`AgentDependencies`](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/core/src/agent/AgentDependencies.ts#L11)  and see where the code breaks.
- [ ] If this results in serious issues, create new tasks for solving those.
- [ ] Solve all issues that came up.
- [ ] Remove the `indy` property from [`AgentDependencies`](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/core/src/agent/AgentDependencies.ts#L11) (if not already done).
- [ ] Remove the `indy` property from the [`node` implementation](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/node/src/index.ts#L18).
- [ ] Remove the `indy` property from the [`react-native` implementation](https://github.com/hyperledger/aries-framework-javascript/blob/c4e96799d8390225ba5aaecced19c79ec1f12fa8/packages/react-native/src/index.ts#L22).

## Example

```ts
import { Agent } from '@aries-framework/core'
import { agentDependencies } from '@aries-framework/node'
import { IndySdkModule } from '@aries-framework/indy-sdk' 

const agent = new Agent({
  dependencies: agentDependencies,
  config: {},
  modules: {
    indy: new IndySdkModule(), // doesn't expose public api
  }
})
```

**Comment by TimoGlastra** [comment]
One addition to this is that we import types from the 'indy-sdk' in quite some places. All types that we need from the indy-sdk should probably just be copied to AFJ and the related packages (I think the AnonCreds related types are already mostly copied in the anoncreds interfaces)
