### ISSUE TITLE
Create AskarWallet in AFJ

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#1165]
### Description
In order to move towards the complete removal of the dependency on `indy-sdk`, we need to replace its storage/wallet related functionality by leveraging the [`aries-askar`](https://github.com/hyperledger/aries-askar) Rust package. This functionality will be handled by a new and separate package called `@aries-framwork/aries-askar`. This package will interface with the `aries-askar`'s [JavaScript wrapper](https://github.com/hyperledger/aries-askar/tree/main/wrappers/javascript) and match the [Wallet](https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/wallet/Wallet.ts) interface.

### Todo

- [ ] Create a new package called `@aries-framwork/aries-askar`.
    - Alternatively, you can copy and modify one of the existing packages, this saves you some TypeScript, ESLint and Jest configuration.
- [ ] Add the [JavaScript wrapper](https://github.com/hyperledger/aries-askar/tree/main/wrappers/javascript) dependency and verify that everything works as expected.
- [ ] Create a class called `AskarWallet` that implements the [Wallet](https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/wallet/Wallet.ts) interface and implement all methods.
- [ ] Write tests
