### ISSUE TITLE
Properly validate sender of message before attaching connection to context

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript#76]
Per the [connection response](https://github.com/hyperledger/aries-rfcs/tree/master/features/0160-connection-protocol#2-connection-response) message in the connection RFC:

> The signature data must be used to verify against the invitation's recipientKeys for continuity.

This means we should check if the `connection~sig` field is signed with the same (one of?) the key(s) as the `recipientKeys` from the invitation.

As we discussed on the call:
- [x] don't store `theirDidDoc` until the signed connection response is verified against `recipientKeys` from the invitation . Until then use the `recipientKeys` from the invitation thats stored with the connection record. (#98)
- [x] store the invitation with the connection record. This already happens when we create the invitation but when we receive it. (#98)
- [x] Verify that the signer of `connection~sig` from the connection response matches `recipientKeys` from the invitation (#98)
- [x] If we are mid connection protocol and receive a message for a pairwise key that our side generated, the connection associated with that key will be added to the message context. It is validated that the sender key is the same as the key we have stored for that connection, so we know it is the same person sending. However during the connection protocol theirKey is not present yet.  I think the best way to solve this is to only attach the connection if their key is present and validated. This way we won't accidentally attach a connection that is not correct. The connection protocol handler will need to find the connection associated with the message themselves.
