### ISSUE TITLE
Smart schema and credential definition registration

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript#859]
Right now, when registering a schema or credential definition, it makes a request to the ledger to do this without checking if it already exists. This can be quite annoying if you have a script that registers a schema, registers a credential definition and issues a credential based on those afterwards. 

ACA-Py has records for schemas and credential definitions. This way, you can check if you have already created them and if not, fetch them anyways. This does add some complexity, but can be split-up into the schema and credential definitio part.

## TODO

- [ ] Create an `AnonCredsSchemaRecord` in the `modules/indy/repository` directory
  - should have `schemaId`, `schemaIssuerDid`, `schemaName` and `schemaVersion` as tags
- [ ] Create an `AnonCredsSchemaRepository` in the `modules/indy/repository` directory
  - [ ] Add `getBySchemaId` convenience method (that wraps `getSingleByQuery`)
- [ ] Create an `AnonCredsCredentialDefinitionRecord` in the `modules/indy/repository` directory
  - should have `credentialDefinitionId`, `issuerDid`, `schemaId` and `tag` as tags (Q: do we also want `schemaIssuerDid`, `schemaName` and `schemaVersion`? ACA-Py has it but doesn't seem necessary to me)
- [ ] Create an `AnonCredsCredentialDefinitionRepository` in the `modules/indy/repository` directory
  - [ ] Add `getByCredentialDefinitionId` convenience method (that wraps `getSingleByQuery`)
- [ ] Update the ledger module (or service? input needed) to integrate with the `AnonCredsSchemaRepository` and `AnonCredsCredentialDefinitionRepository`
	- When creating a schema or credential definition, create the `schemaId` or `credentialDefinitionId` respectively.
  	  - schemaId = `${issuerDid}:2:${schemaName}:${schemaVersion}`
  	  - credentialDefinitionId = `${issuerDid}:3:CL:${schema.seqNo}:${tag}`
	- check in the `AnonCredsSchemaRepository` or `AnonCredsCredentialDefinitionRepository` respectively whether the schema or credential definition already exists in storage.
	- If it exists, return the schema/cred def exactly as it would be returned if we would register it on the ledger (there should be NO difference in the API)
	- it it does not exists, register the schema/cred def as usual and register the schema/cred def in the repository as a `AnonCredsSchemaRecord` or `AnonCredsCredentialDefinitionRecord`
- [ ] Add tests for the records, repository and new 'caching' method in the `registerSchema` / `registerCredentialDefinition`
- [ ] Store which anoncreds resource server a schema / credential definition is anchored on https://anoncreds-wg.github.io/anoncreds-spec/
  - [ ] TODO: how do we store the resource server from which the anoncreds objects are resolved (full did?)

This is really useful as it would allow you to retrieve all schemas/credential defitions you have created (like acapy supports)

This issue can be split up into two PRs, one for the schema and one for the credential defintiion

**Comment by morrieinmaas** [comment]
> 
> ACA-Py has records for schemas and credential definitions. This way, you can check if you have already created them and if not, fetch them anyways. This does add some complexity, but can be split-up into the schema and credential definitio part.

@blu3beri do you mean `and if so, fetch them anyways` instead of `and if not, fetch them anyways`?

**Comment by TimoGlastra** [comment]
For schemas, yes that would work. For credential definitions we should throw an error in case 2.

**Comment by genaris** [comment]
Guys, could this be considered as closed provided #900 is merged, or there is something else missing?

**Comment by blu3beri** [comment]
Closed as #900 is merged.
